import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations{

  @override
  Map<String, Map<String,String>> get keys =>{
    'en':{
      'Raithan' : 'Raithan Agri Logistic Private Limited',
      'Business Categories' : 'Business Categories',
      'Mechanics' : 'Mechanics',
      'Paddy Transplantors' : 'Paddy Transplantors',
      'Drones' : 'Drones',
      'Harvestors' : 'Harvestors',
      'Agriculture Labor' : 'Agriculture Labor',
      'Earth Movers' : 'Earth Movers',
      'Implements' : 'Implements',
      'Machines' : 'Machines',
      'Sign In' : 'Sign In',
      'Sign Up' : 'Sign Up',
      'Sign Out' : 'Sign Out',
      'Business' : 'Business',
      'Profile' : 'Profile',
      'Welcome' : 'Welcome',
      'New User? ' : 'New User? ',
      'Phone' : 'Phone',
      'OTP' : 'OTP',
      'Next' : 'Next',
      'You will get 6 digit OTP on your phone' : 'You will get 6 digit OTP on your phone',
      'Phone Number' : 'Phone Number',
      'Please enter a phone number' : 'Please enter a phone number',
      'Please enter a valid phone number' : 'Please enter a valid phone number',
      'OTP sent successfully to' : 'OTP sent successfully to',
      'Resend OTP' : 'Resend OTP',
      'Please enter the OTP' : 'Please enter the OTP',
      'OTP must be 6 digits' : 'OTP must be 6 digits',
      'Already Registered? ' : 'Already Registered? ',
      'Phone  ' : 'Phone  ',
      ' OTP  ' : ' OTP  ',
      '   Profile' : '   Profile',
      'Details' : 'Details',
      'Personal Details' : 'Personal Details',
      'First Name' : 'First Name',
      'Please enter your first name' : 'Please enter your first name',
      'First Name should contain only letter and space' : 'First Name should contain only letter and space',
      'First Name length must be greater than 2' : 'First Name length must be greater than 2',
      'Last Name' : 'Last Name',
      'Please enter your Last name' : 'Please enter your Last name',
      'Last Name should contain only letter and space' : 'Last Name should contain only letter and space',
      'Last Name length must be greater than 2' : 'Last Name length must be greater than 2',
      'Please select your date of birth' : 'Please select your date of birth',
      'Select an Gender' : 'Select an Gender',
      'Please select an option' : 'Please select an option',
      'Please select an image' : 'Please select an image',
      'Upload Image' : 'Upload Image',
      'Select an image' : 'Select an image',
      'Business Name':'Business Name',
      'Please enter your Business name' : 'Please enter your Business name',
      'Business Information' : 'Business Information',
      'Business Address' : 'Business Address',
      'House Number' : 'House Number',
      'Block Number' : 'House Number',
      'Please write your home Number' : 'Please write your home Number',
      'Street' : 'Street',
      'Please write your street' : 'Please write your street',
      'Area' : 'Area',
      'Please write your area' : 'Please write your area',
      'Landmark' : 'Landmark',
      'City' : 'City',
      'Please write your city' : 'Please write your city',
      'State' : 'State',
      'Please write your state' : 'Please write your state',
      'Pincode' : 'Pincode',
      'Please write your pincode' : 'Please write your pincode',
      'Pincode must be 6 digits only' : 'Pincode must be 6 digits only',
      'Working Time' : 'Working Time',
      'Start Time' : 'Start Time',
      'Please Select Start Time' : 'Please Select Start Time',
      'End Time' : 'End Time',
      'Please Select End Time' : 'Please Select End Time',
      'Select Working Days' : 'Select Working Days',
      'Birth Year' : 'Birth Year',
      'Year of Birth' : 'Year of Birth',
      'Gender' : 'Gender',
      'Cancel' : 'Cancel',
      'Apply For Verification' : 'Apply For Verification',
      'Edit' : 'Edit',
      'Categories' : 'Categories',
      'Working Days' : 'Working Days',
      'Update Location' : 'Update Location',
      'updateLocationConfirmationText' : 'This is for your exact business location. are you sure this is your exact business location?',
      'Yes' : 'Yes',
      'No' : 'No' ,
      'Edit Business Details' : 'Edit Business Details',
      'Model No' : 'Model No',
      'HP' : 'HP',
      'Type' : 'Type',
      'Rate Us':'Rate Us',
      'Call Now' : 'Call Now',
      'Write Your Phone Number' : 'Enter Your Phone Number',
      'We will send you an OTP to verify your phone number.' : 'We will send you an OTP to verify your phone number.',
      'Submit' : 'Submit',
      'Enter OTP' : 'Enter OTP',
      'We have sent a 6-digit OTP to your phone number.' : 'We have sent a 6-digit OTP to your phone number.',
      'Provide Your Feedback' : 'Provide Your Feedback',
      'Please rate your experience with the service.' : 'Please rate your experience with the service.',
      'eShram Card' : 'eShram Card',
      'Ready to travel within 10 km' : 'Ready to travel within 10 km',
      'Not ready to travel beyond current location' : 'Not ready to travel beyond current location',
      'Individual Worker' : 'Individual Worker',
      'Workers' : 'Workers',
      'Please write number of workers' : 'Please write number of workers',
      'Please enter a valid number' : 'Please enter a valid number',
      'No of Workers' : 'No of Workers',
      'Please enter your Shram Card Number' : 'Please enter your Shram Card Number',
      'Shram Card Number must be 12 digits long' : 'Shram Card Number must be 12 digits long',
      'Shram Card Number must be a valid number' : 'Shram Card Number must be a valid number',
      'Shram Card Number' : 'Shram Card Number',
      'Service Type' : 'Service Type',
      'Shram Card Image' : 'Shram Card Image',
      'Horse Power' : 'Horse Power',
      'Distance' : 'Distance',
      'Select' : 'Select',
      'Sowing Drylands' : 'Sowing Drylands',
      'Transplantation Wetlands' : 'Transplantation Wetlands',
      'Weeding Drylands' : 'Weeding Drylands',
      'Weeding Wetlands' : 'Weeding Wetlands',
      'Fertilization Drylands' : 'Fertilization Drylands',
      'Fertilization Wetlands' : 'Fertilization Wetlands',
      'Spraying Drylands with Hand pump' : 'Spraying Drylands with Hand pump',
      'Spraying Drylands with Battery pump' : 'Spraying Drylands with Battery pump',
      'Spraying Drylands with Petrol pump' : 'Spraying Drylands with Petrol pump',
      'Spraying Wetlands with Hand pump' : 'Spraying Wetlands with Hand pump',
      'Spraying Wetlands with Battery pump' : 'Spraying Wetlands with Battery pump',
      'Spraying Wetlands with Petrol pump' : 'Spraying Wetlands with Petrol pump',
      'Harvesting Commercial Crops' : 'Harvesting Commercial Crops',
      'Harvesting Fruits Crops' : 'Harvesting Fruits Crops',
      'Harvesting Vegetables Crops' : 'Harvesting Vegetables Crops',
      'Harvesting Crops' : 'Harvesting Crops',
      'Electric Water Pump' : 'Electric Water Pump',
      'Tractor Repair' : 'Tractor Repair',
      'Solar Water Pump' : 'Solar Water Pump',
      'Diesel Water Pump' : 'Diesel Water Pump',
      'Tyre' : 'Tyre',
      'Chain' : 'Chain',
      'Farmer Monitoring' : 'Farmer Monitoring',
      'For Spraying' : 'For Spraying',
      'Verified' : 'Verified',
      'Unverified' : 'Unverified',
      'Rejected' : 'Rejected',
      'Reverification Required' : 'Reverification Required',
      'Modification Required' : 'Modification Required',
      'Blocked': 'Blocked',
      'Reverification' : 'Reverification',
      'Modification' : 'Modification',
      'Required' : 'Required',
      'Monday' : 'Monday',
      'Tuesday' : 'Tuesday',
      'Wednesday' : 'Wednesday',
      'Thursday' : 'Thursday',
      'Friday' : 'Friday',
      'Saturday' : 'Saturday',
      'Sunday' : 'Sunday',
      'Male' : 'Male',
      'Female' : 'Female',
      'Other' : 'Other',
      'Driving License Image' : 'Driving License Image',
      'Right View Image' : 'Right View Image',
      'Drone Bill Image' : 'Drone Bill Image',
      'RC Book Image' : 'RC Book Image',
      'Back View Image':'Back View Image',
      'Left View Image' :'Left View Image',
      'Front View Image' : 'Front View Image',
      'Select an' : 'Select an',
      'Please write horse power' : 'Please write horse power',
      'Horse power must be a valid number' : 'Horse power must be a valid number',
      'Please write Model Number' : 'Please write Model Number',
      'Select an Business Type' : 'Select an Business Type',
      'Business - Unregistered' : 'Business - Unregistered',
      'Business - Registered / Proprietorship' : 'Business - Registered / Proprietorship',
      'Business - Registered / Partnership' : 'Business - Registered / Partnership',
      'Business - Registered / Pvt Ltd' : 'Business - Registered / Pvt Ltd',
      'Individual' : 'Individual',
      'Individual Consultant' : 'Individual Consultant',
      'Business Type' : 'Business Type',
      'Business Name ( Optional )' : 'Business Name ( Optional )',
      'No products have been added yet, ' : 'No products have been added yet, ',
      'so no categories are available.' : 'so no categories are available.',
      'No Products' : 'No Products'

    },
    'hi': {
      'Raithan': 'रैथान',
      'Business Categories': 'बिजनेस कैटेगरी',
      'Mechanics': 'मेकैनिक्स',
      'Paddy Transplantors': 'धान रोपाई करने वाले',
      'Drones': 'ड्रोन',
      'Harvestors': 'कटाई मशीनें',
      'Agriculture Labor': 'कृषि मजदूर',
      'Earth Movers': 'मिट्टी हटाने वाली मशीनें',
      'Implements': 'कृषि यंत्र',
      'Machines': 'मशीनें',
      'Sign In': 'साइन इन करें',
      'Sign Up': 'साइन अप करें',
      'Sign Out': 'साइन आउट करें',
      'Business': 'बिजनेस',
      'Profile': 'प्रोफाइल',
      'Welcome': 'स्वागत है',
      'New User? ': 'नया यूजर?',
      'Phone': 'फोन',
      'OTP': 'ओटीपी',
      'Next': 'आगे',
      'You will get 6 digit OTP on your phone': 'आपके फोन पर 6 अंकों का ओटीपी मिलेगा',
      'Phone Number': 'फोन नंबर',
      'Please enter a phone number': 'कृपया फोन नंबर डालें',
      'Please enter a valid phone number': 'कृपया सही फोन नंबर डालें',
      'OTP sent successfully to': 'ओटीपी भेजा गया',
      'Resend OTP': 'ओटीपी दोबारा भेजें',
      'Please enter the OTP': 'कृपया ओटीपी डालें',
      'OTP must be 6 digits': 'ओटीपी 6 अंकों का होना चाहिए',
      'Already Registered? ': 'पहले से रजिस्टर?',
      'Phone  ': 'फोन',
      ' OTP  ': 'ओटीपी',
      '   Profile': 'प्रोफाइल',
      'Details': 'जानकारी',
      'Personal Details': 'पर्सनल डिटेल्स',
      'First Name': 'पहला नाम',
      'Please enter your first name': 'कृपया पहला नाम डालें',
      'First Name should contain only letter and space': 'पहले नाम में केवल अक्षर और स्पेस होने चाहिए',
      'First Name length must be greater than 2': 'पहले नाम की लंबाई 2 से ज्यादा होनी चाहिए',
      'Last Name': 'अंतिम नाम',
      'Please enter your Last name': 'कृपया अंतिम नाम डालें',
      'Last Name should contain only letter and space': 'अंतिम नाम में केवल अक्षर और स्पेस होने चाहिए',
      'Last Name length must be greater than 2': 'अंतिम नाम की लंबाई 2 से ज्यादा होनी चाहिए',
      'Please select your date of birth': 'कृपया अपनी जन्म तिथि चुनें',
      'Select an Gender': 'लिंग चुनें',
      'Please select an option': 'कृपया एक विकल्प चुनें',
      'Please select an image': 'कृपया एक फोटो चुनें',
      'Upload Image': 'फोटो अपलोड करें',
      'Select an image': 'एक फोटो चुनें',
      'Business Name': 'बिजनेस का नाम',
      'Please enter your Business name': 'कृपया बिजनेस का नाम डालें',
      'Business Information': 'बिजनेस की जानकारी',
      'Business Address': 'बिजनेस का पता',
      'House Number': 'मकान नंबर',
      'Block Number': 'ब्लॉक नंबर',
      'Please write your home Number': 'कृपया मकान नंबर लिखें',
      'Street': 'गली',
      'Please write your street': 'कृपया गली का नाम लिखें',
      'Area': 'इलाका',
      'Please write your area': 'कृपया इलाका लिखें',
      'Landmark': 'नज़दीकी जगह',
      'City': 'शहर',
      'Please write your city': 'कृपया शहर का नाम लिखें',
      'State': 'राज्य',
      'Please write your state': 'कृपया राज्य का नाम लिखें',
      'Pincode': 'पिन कोड',
      'Please write your pincode': 'कृपया पिन कोड लिखें',
      'Pincode must be 6 digits only': 'पिन कोड सिर्फ 6 अंकों का होना चाहिए',
      'Working Time': 'काम का समय',
      'Start Time': 'शुरू करने का समय',
      'Please Select Start Time': 'कृपया शुरू करने का समय चुनें',
      'End Time': 'समाप्ति का समय',
      'Please Select End Time': 'कृपया समाप्ति का समय चुनें',
      'Select Working Days': 'काम करने के दिन चुनें',
      'Birth Year': 'जन्म वर्ष',
      'Year of Birth': 'जन्म का वर्ष',
      'Gender': 'लिंग',
      'Cancel': 'रद्द करें',
      'Apply For Verification': 'सत्यापन के लिए आवेदन करें',
      'Edit': 'संपादित करें',
      'Categories': 'श्रेणियाँ',
      'Working Days': 'काम के दिन',
      'Update Location': 'लोकेशन अपडेट करें',
      'updateLocationConfirmationText': 'यह आपके बिजनेस का सही लोकेशन है। क्या यह सही लोकेशन है?',
      'Yes': 'हां',
      'No': 'नहीं',
      'Edit Business Details': 'बिजनेस की जानकारी संपादित करें',
      'Model No': 'मॉडल नंबर',
      'HP': 'एचपी',
      'Type': 'प्रकार',
      'Rate Us': 'हमें रेट करें',
      'Call Now': 'अभी कॉल करें',
      'Write Your Phone Number': 'अपना फोन नंबर लिखें',
      'We will send you an OTP to verify your phone number.': 'हम आपके फोन नंबर को सत्यापित करने के लिए ओटीपी भेजेंगे।',
      'Submit': 'सबमिट करें',
      'Enter OTP': 'ओटीपी डालें',
      'We have sent a 6-digit OTP to your phone number.': 'हमने आपके फोन नंबर पर 6 अंकों का ओटीपी भेजा है।',
      'Provide Your Feedback': 'अपनी प्रतिक्रिया दें',
      'Please rate your experience with the service.': 'कृपया सेवा का अनुभव रेट करें।',
      'eShram Card': 'ई-श्रम कार्ड',
      'Ready to travel within 10 km': '10 किमी के भीतर यात्रा करने के लिए तैयार',
      'Not ready to travel beyond current location': 'वर्तमान स्थान से आगे यात्रा के लिए तैयार नहीं',
      'Individual Worker': 'व्यक्तिगत मजदूर',
      'Workers': 'मजदूर',
      'Please write number of workers': 'कृपया मजदूरों की संख्या लिखें',
      'Please enter a valid number': 'कृपया सही नंबर डालें',
      'No of Workers': 'मजदूरों की संख्या',
      'Please enter your Shram Card Number': 'कृपया अपना श्रम कार्ड नंबर डालें',
      'Shram Card Number must be 12 digits long': 'श्रम कार्ड नंबर 12 अंकों का होना चाहिए',
      'Shram Card Number must be a valid number': 'श्रम कार्ड नंबर सही होना चाहिए',
      'Shram Card Number': 'श्रम कार्ड नंबर',
      'Service Type': 'सेवा का प्रकार',
      'Shram Card Image': 'श्रम कार्ड की फोटो',
      'Horse Power': 'हॉर्स पावर',
      'Distance': 'दूरी',
      'Select': 'चुनें',
      'Sowing Drylands': 'सूखी जमीन में बुवाई',
      'Transplantation Wetlands': 'गीली जमीन में रोपाई',
      'Weeding Drylands': 'सूखी जमीन में निराई',
      'Weeding Wetlands': 'गीली जमीन में निराई',
      'Fertilization Drylands': 'सूखी जमीन में खाद डालना',
      'Fertilization Wetlands': 'गीली जमीन में खाद डालना',
      'Spraying Drylands with Hand pump': 'हैंड पंप से सूखी जमीन में छिड़काव',
      'Spraying Drylands with Battery pump': 'बैटरी पंप से सूखी जमीन में छिड़काव',
      'Spraying Drylands with Petrol pump': 'पेट्रोल पंप से सूखी जमीन में छिड़काव',
      'Spraying Wetlands with Hand pump': 'हैंड पंप से गीली जमीन में छिड़काव',
      'Spraying Wetlands with Battery pump': 'बैटरी पंप से गीली जमीन में छिड़काव',
      'Spraying Wetlands with Petrol pump': 'पेट्रोल पंप से गीली जमीन में छिड़काव',
      'Harvesting Commercial Crops': 'वाणिज्यिक फसलों की कटाई',
      'Harvesting Fruits Crops': 'फलों की फसल की कटाई',
      'Harvesting Vegetables Crops': 'सब्जियों की फसल की कटाई',
      'Harvesting Crops': 'फसलों की कटाई',
      'Electric Water Pump': 'इलेक्ट्रिक वाटर पंप',
      'Tractor Repair': 'ट्रैक्टर रिपेयर',
      'Solar Water Pump': 'सोलर वाटर पंप',
      'Diesel Water Pump': 'डीजल वाटर पंप',
      'Tyre': 'टायर',
      'Chain': 'चेन',
      'Farmer Monitoring': 'किसान निगरानी',
      'For Spraying': 'स्प्रे के लिए',
      'Verified': 'सत्यापित',
      'Unverified': 'असत्यापित',
      'Rejected': 'अस्वीकृत',
      'Reverification Required': 'पुनः सत्यापन आवश्यक',
      'Modification Required': 'संशोधन आवश्यक',
      'Blocked': 'ब्लॉक किया गया',
      'Reverification': 'पुनः सत्यापन',
      'Modification': 'संशोधन',
      'Required': 'आवश्यक',
      'Monday': 'सोमवार',
      'Tuesday': 'मंगलवार',
      'Wednesday': 'बुधवार',
      'Thursday': 'गुरुवार',
      'Friday': 'शुक्रवार',
      'Saturday': 'शनिवार',
      'Sunday': 'रविवार',
      'Male': 'पुरुष',
      'Female': 'महिला',
      'Other': 'अन्य',
      'Driving License Image': 'ड्राइविंग लाइसेंस की फोटो',
      'Right View Image': 'दाएं तरफ की फोटो',
      'Drone Bill Image': 'ड्रोन बिल की फोटो',
      'RC Book Image': 'आरसी बुक की फोटो',
      'Back View Image': 'पीछे की फोटो',
      'Left View Image': 'बाएं तरफ की फोटो',
      'Front View Image': 'सामने की फोटो',
      'Select an': 'चुनें',
      'Please write horse power': 'कृपया हॉर्स पावर लिखें',
      'Horse power must be a valid number': 'हॉर्स पावर एक सही संख्या होनी चाहिए',
      'Please write Model Number': 'कृपया मॉडल नंबर लिखें',
      'Select an Business Type': 'एक व्यवसाय प्रकार चुनें',
      'Business - Unregistered': 'व्यवसाय - अपंजीकृत',
      'Business - Registered / Proprietorship': 'व्यवसाय - पंजीकृत / स्वामित्व',
      'Business - Registered / Partnership': 'व्यवसाय - पंजीकृत / साझेदारी',
      'Business - Registered / Pvt Ltd': 'व्यवसाय - पंजीकृत / प्रा. लि.',
      'Individual': 'व्यक्ति',
      'Individual Consultant': 'स्वतंत्र सलाहकार',
      'Business Type': 'व्यवसाय प्रकार',
      'Business Name ( Optional )': 'व्यवसाय का नाम (वैकल्पिक)',
      'No products have been added yet, ': 'अभी तक कोई उत्पाद नहीं जोड़ा गया है, ',
      'so no categories are available.': 'इसलिए कोई श्रेणियां उपलब्ध नहीं हैं।',
      'No Products': 'कोई उत्पाद नहीं'

    },
    'te': { 'Raithan': 'రైతన్',
      'Business Categories': 'వ్యవసాయ విభాగాలు',
      'Mechanics': 'యాంత్రికులు',
      'Paddy Transplantors': 'నాటు యంత్రాలు',
      'Drones': 'డ్రోన్లు',
      'Harvestors': 'పంటలు కోసే యంత్రాలు',
      'Agriculture Labor': 'వ్యవసాయ కార్మికులు',
      'Earth Movers': 'భూమి తరలింపు యంత్రాలు',
      'Implements': 'ఉపకరణాలు',
      'Machines': 'యంత్రాలు',
      'Sign In': 'ప్రవేశించండి',
      'Sign Up': 'చేరండి',
      'Sign Out': 'బయటకు వెళ్లండి',
      'Business': 'వ్యాపారం',
      'Profile': 'ప్రొఫైల్',
      'Welcome': 'స్వాగతం',
      'New User? ': 'క్రొత్త వినియోగదారా? ',
      'Phone': 'ఫోన్',
      'OTP': 'ఓటిపి',
      'Next': 'తర్వాత',
      'You will get 6 digit OTP on your phone': 'మీ ఫోన్‌కు 6 అంకెల ఓటిపి వస్తుంది',
      'Phone Number': 'ఫోన్ నంబర్',
      'Please enter a phone number': 'దయచేసి ఫోన్ నంబర్‌ను నమోదు చేయండి',
      'Please enter a valid phone number': 'దయచేసి సరైన ఫోన్ నంబర్‌ను నమోదు చేయండి',
      'OTP sent successfully to': 'ఓటిపి విజయవంతంగా పంపించబడింది',
      'Resend OTP': 'ఓటిపి మళ్లీ పంపండి',
      'Please enter the OTP': 'దయచేసి ఓటిపి‌ని నమోదు చేయండి',
      'OTP must be 6 digits': 'ఓటిపి 6 అంకెలుగా ఉండాలి',
      'Already Registered? ': 'ఇప్పటికే నమోదు చేసుకున్నారా? ',
      'Phone  ': 'ఫోన్  ',
      ' OTP  ': ' ఓటిపి  ',
      '   Profile': '   ప్రొఫైల్',
      'Details': 'వివరాలు',
      'Personal Details': 'వ్యక్తిగత వివరాలు',
      'First Name': 'మొదటి పేరు',
      'Please enter your first name': 'దయచేసి మీ మొదటి పేరును నమోదు చేయండి',
      'First Name should contain only letter and space': 'మొదటి పేరు అక్షరాలు మరియు ఖాళీలను మాత్రమే కలిగి ఉండాలి',
      'First Name length must be greater than 2': 'మొదటి పేరు పొడవు 2 కంటే ఎక్కువగా ఉండాలి',
      'Last Name': 'చివరి పేరు',
      'Please enter your Last name': 'దయచేసి మీ చివరి పేరును నమోదు చేయండి',
      'Last Name should contain only letter and space': 'చివరి పేరు అక్షరాలు మరియు ఖాళీలను మాత్రమే కలిగి ఉండాలి',
      'Last Name length must be greater than 2': 'చివరి పేరు పొడవు 2 కంటే ఎక్కువగా ఉండాలి',
      'Please select your date of birth': 'దయచేసి మీ పుట్టిన తేదీని ఎంచుకోండి',
      'Select an Gender': 'లింగాన్ని ఎంచుకోండి',
      'Please select an option': 'దయచేసి ఒక ఎంపికను ఎంచుకోండి',
      'Please select an image': 'దయచేసి ఒక చిత్రం ఎంచుకోండి',
      'Upload Image': 'చిత్రాన్ని అప్‌లోడ్ చేయండి',
      'Select an image': 'చిత్రాన్ని ఎంచుకోండి',
      'Business Name': 'వ్యాపారం పేరు',
      'Please enter your Business name': 'దయచేసి మీ వ్యాపార పేరును నమోదు చేయండి',
      'Business Information': 'వ్యాపార సమాచారం',
      'Business Address': 'వ్యాపార చిరునామా',
      'House Number': 'ఇల్లు నంబర్',
      'Block Number': 'బ్లాక్ నంబర్',
      'Please write your home Number': 'దయచేసి మీ ఇల్లు నంబర్‌ను వ్రాయండి',
      'Street': 'వీధి',
      'Please write your street': 'దయచేసి మీ వీధిని వ్రాయండి',
      'Area': 'ప్రాంతం',
      'Please write your area': 'దయచేసి మీ ప్రాంతాన్ని వ్రాయండి',
      'Landmark': 'ప్రత్యేక గుర్తు',
      'City': 'నగరం',
      'Please write your city': 'దయచేసి మీ నగరాన్ని వ్రాయండి',
      'State': 'రాష్ట్రం',
      'Please write your state': 'దయచేసి మీ రాష్ట్రాన్ని వ్రాయండి',
      'Pincode': 'పిన్‌కోడ్',
      'Please write your pincode': 'దయచేసి మీ పిన్‌కోడ్‌ను వ్రాయండి',
      'Pincode must be 6 digits only': 'పిన్‌కోడ్ 6 అంకెలుగా మాత్రమే ఉండాలి',
      'Working Time': 'పని సమయం',
      'Start Time': 'ప్రారంభ సమయం',
      'Please Select Start Time': 'దయచేసి ప్రారంభ సమయాన్ని ఎంచుకోండి',
      'End Time': 'ముగింపు సమయం',
      'Please Select End Time': 'దయచేసి ముగింపు సమయాన్ని ఎంచుకోండి',
      'Select Working Days': 'పని రోజులను ఎంచుకోండి',
      'Birth Year': 'పుట్టిన సంవత్సరం',
      'Year of Birth': 'పుట్టిన సంవత్సరం',
      'Gender': 'లింగం',
      'Cancel': 'రద్దు చేయండి',
      'Apply For Verification': 'నిర్ధారణకు దరఖాస్తు చేయండి',
      'Edit': 'మార్చండి',
      'Categories': 'వర్గాలు',
      'Working Days': 'పని దినాలు',
      'Update Location': 'చిరునామాను నవీకరించండి',
      'updateLocationConfirmationText': 'ఇది మీ ఖచ్చితమైన వ్యాపార స్థానం కోసం. ఇది మీ ఖచ్చితమైన స్థలమా?',
      'Yes': 'అవును',
      'No': 'కాదు',
      'Edit Business Details': 'వ్యాపార వివరాలను మార్చండి',
      'Model No': 'మోడల్ నంబర్',
      'HP': 'హెచ్‌పి',
      'Type': 'రకం',
      'Rate Us': 'రేటింగ్',
      'Call Now': 'కాల్ చేయండి',
      'Write Your Phone Number': 'మీ ఫోన్ నంబర్‌ను నమోదు చేయండి',
      'We will send you an OTP to verify your phone number.': 'మీ ఫోన్ నంబర్‌ను నిర్ధారించడానికి మేము ఓటిపి పంపుతాము.',
      'Submit': 'సమర్పించండి',
      'Enter OTP': 'ఓటిపి నమోదు చేయండి',
      'We have sent a 6-digit OTP to your phone number.': 'మేము మీ ఫోన్ నంబర్‌కు 6 అంకెల ఓటిపి పంపాము.',
      'Provide Your Feedback': 'మీ అభిప్రాయం తెలపండి',
      'Please rate your experience with the service.': 'సేవలో మీ అనుభవానికి రేటింగ్ ఇవ్వండి.',
      'eShram Card': 'ఈశ్రమ్ కార్డు',
      'Ready to travel within 10 km': '10 కి.మీ లోపల ప్రయాణించడానికి సిద్ధంగా ఉన్నారు',
      'Not ready to travel beyond current location': 'ప్రస్తుత స్థలాన్ని మించుకొని ప్రయాణించడానికి సిద్ధంగా లేరు',
      'Individual Worker': 'వ్యక్తిగత కార్మికుడు',
      'Workers': 'కార్మికులు',
      'Please write number of workers': 'దయచేసి కార్మికుల సంఖ్యను వ్రాయండి',
      'Please enter a valid number': 'దయచేసి చెల్లుబాటైన సంఖ్యను నమోదు చేయండి',
      'No of Workers': 'కార్మికుల సంఖ్య',
      'Please enter your Shram Card Number': 'దయచేసి మీ శ్రామ్ కార్డ్ నంబర్‌ను నమోదు చేయండి',
      'Shram Card Number must be 12 digits long': 'శ్రామ్ కార్డ్ నంబర్ 12 అంకెలుగా ఉండాలి',
      'Shram Card Number must be a valid number': 'శ్రామ్ కార్డ్ నంబర్ చెల్లుబాటు కావాలి',
      'Shram Card Number': 'శ్రామ్ కార్డ్ నంబర్',
      'Service Type': 'సేవ రకం',
      'Shram Card Image': 'శ్రామ్ కార్డ్ చిత్రం',
      'Horse Power': 'హార్స్ పవర్',
      'Distance': 'దూరం',
      'Select': 'ఎంచుకోండి',
      'Sowing Drylands': 'ఎండిపోయిన భూముల్లో విత్తనాలు నాటడం',
      'Transplantation Wetlands': 'నీటి భూముల్లో నాటడం',
      'Weeding Drylands': 'ఎండిపోయిన భూముల్లో గడ్డిని తీసివేయడం',
      'Weeding Wetlands': 'నీటి భూముల్లో గడ్డిని తీసివేయడం',
      'Fertilization Drylands': 'ఎండిపోయిన భూముల్లో ఎరువులు వేయడం',
      'Fertilization Wetlands': 'నీటి భూముల్లో ఎరువులు వేయడం',
      'Spraying Drylands with Hand pump': 'హ్యాండ్ పంప్‌తో ఎండిపోయిన భూముల్లో పిచికారి',
      'Spraying Drylands with Battery pump': 'బ్యాటరీ పంప్‌తో ఎండిపోయిన భూముల్లో పిచికారి',
      'Spraying Drylands with Petrol pump': 'పెట్రోల్ పంప్‌తో ఎండిపోయిన భూముల్లో పిచికారి',
      'Spraying Wetlands with Hand pump': 'హ్యాండ్ పంప్‌తో నీటి భూముల్లో పిచికారి',
      'Spraying Wetlands with Battery pump': 'బ్యాటరీ పంప్‌తో నీటి భూముల్లో పిచికారి',
      'Spraying Wetlands with Petrol pump': 'పెట్రోల్ పంప్‌తో నీటి భూముల్లో పిచికారి',
      'Harvesting Commercial Crops': 'వాణిజ్య పంటలను కోయడం',
      'Harvesting Fruits Crops': 'పండ్ల పంటలను కోయడం',
      'Harvesting Vegetables Crops': 'కూరగాయల పంటలను కోయడం',
      'Harvesting Crops': 'పంటలను కోయడం',
      'Electric Water Pump': 'విద్యుత్ నీటిపంపు',
      'Tractor Repair': 'ట్రాక్టర్ మరమ్మత్తు',
      'Solar Water Pump': 'సౌర నీటిపంపు',
      'Diesel Water Pump': 'డీజిల్ నీటిపంపు',
      'Tyre': 'టైర్',
      'Chain': 'చెయిన్',
      'Farmer Monitoring': 'రైతు పరిశీలన',
      'For Spraying': 'పిచికారి కోసం',
      'Verified': 'నిర్ధారించబడింది',
      'Unverified': 'నిర్ధారణ చేయబడలేదు',
      'Rejected': 'తిరస్కరించబడింది',
      'Reverification Required': 'మళ్ళీ నిర్ధారణ అవసరం',
      'Modification Required': 'మార్పు అవసరం',
      'Blocked': 'నిరోధించబడింది',
      'Reverification': 'మళ్ళీ నిర్ధారణ',
      'Modification': 'మార్పు',
      'Required': 'అవసరం',
      'Monday': 'సోమవారం',
      'Tuesday': 'మంగళవారం',
      'Wednesday': 'బుధవారం',
      'Thursday': 'గురువారం',
      'Friday': 'శుక్రవారం',
      'Saturday': 'శనివారం',
      'Sunday': 'ఆదివారం',
      'Male': 'పురుషుడు',
      'Female': 'స్త్రీ',
      'Other': 'ఇతరులు',
      'Driving License Image': 'డ్రైవింగ్ లైసెన్స్ చిత్రం',
      'Right View Image': 'కుడి వైపు చిత్రం',
      'Drone Bill Image': 'డ్రోన్ల బిల్ చిత్రం',
      'RC Book Image': 'ఆర్సీ బుక్ చిత్రం',
      'Back View Image': 'వెనుక వైపు చిత్రం',
      'Left View Image': 'ఎడమ వైపు చిత్రం',
      'Front View Image': 'ముందు వైపు చిత్రం',
      'Select an': 'ఒకదాన్ని ఎంచుకోండి',
      'Please write horse power': 'దయచేసి హార్స్ పవర్‌ను వ్రాయండి',
      'Horse power must be a valid number': 'హార్స్ పవర్ చెల్లుబాటు అయ్యే సంఖ్యగా ఉండాలి',
      'Please write Model Number': 'దయచేసి మోడల్ నంబర్‌ను వ్రాయండి',
      'Select an Business Type': 'వ్యాపార రకాన్ని ఎంచుకోండి',
      'Business - Unregistered': 'వ్యాపారం - నమోదు చేయబడలేదు',
      'Business - Registered / Proprietorship': 'వ్యాపారం - నమోదు చేయబడింది / యాజమాన్యం',
      'Business - Registered / Partnership': 'వ్యాపారం - నమోదు చేయబడింది / భాగస్వామ్యం',
      'Business - Registered / Pvt Ltd': 'వ్యాపారం - నమోదు చేయబడింది / ప్రైవేట్ లిమిటెడ్',
      'Individual': 'వ్యక్తిగత',
      'Individual Consultant': 'వ్యక్తిగత సలహాదారు',
      'Business Type': 'వ్యాపార రకం',
      'Business Name ( Optional )': 'వ్యాపార పేరు ( ఐచ్ఛికం )',
      'No products have been added yet, ': 'ఇప్పటివరకు ఎలాంటి ఉత్పత్తులు జోడించబడలేదు, ',
      'so no categories are available.': 'కాబట్టి ఎలాంటి వర్గాలు అందుబాటులో లేవు.',
      'No Products': 'ఎలాంటి ఉత్పత్తులు లేవు'
    }

  };
}